### ISSUE TITLE
`ip` not installed in image `icr.io/appcafe/open-liberty:full-java11-openj9-ubi`

### ISSUE THREAD

**Issue by tstephen** [OpenLiberty/guide-containerize-podman#28]
When following guide: https://openliberty.io/guides/containerize-podman.html#running-the-tests

Steps:
1. I created and ran the images successfully.
    ```
    CONTAINER ID  IMAGE                             COMMAND               CREATED         STATUS             PORTS                   NAMES
    939ae052d878  localhost/system:1.0-SNAPSHOT     /opt/ol/wlp/bin/s...  18 minutes ago  Up 18 minutes ago  0.0.0.0:9080->9080/tcp system
    5daadba76ec1  localhost/inventory:1.0-SNAPSHOT  /opt/ol/wlp/bin/s...  18 minutes ago  Up 18 minutes ago  0.0.0.0:9081->9081/tcp inventory
    ```
2. But when trying to get the IP address of the `system` image there was nothing returned

3. Eventually, we found https://github.com/containers/podman/issues/679 and diagnosed with `/usr/bin/podman exec system ip addr show eth0`, which returned:
    ```
    Error: executable file `ip` not found in $PATH: No such file or directory: OCI runtime attempted to invoke a command that was not found
    ```

**Conclusion** Need to install `ip` in this image.

**Comment by shin19991207** [comment]
Hello @tstephen

Can you elaborate on which platform you were using to run the guide (Windows, Linux, or Mac)?

Thanks.

**Comment by tstephen** [comment]
Linux, though why is that related to the error inside the container? BTW this occurred during Emily Jiang's workshop at JAX London and she helped me diagnose.

**Comment by shin19991207** [comment]
The error might or might not related to the platform used. It was just that I tried to reproduce the problem but it works without error on my end (MacOS), and thus I thought it would be great to reproduce the problem using the same platform/settings as yours.

Did Emily come up with a solution for the issue?

We will investigate further and let you know the result. Thanks.

**Comment by gkwan-ibm** [comment]
I have no problem to get the ip address by the following command on Ubantu and CentOS. The `system` container does not have `ip` command.
```
podman inspect -f "{{.NetworkSettings.IPAddress }}" system
```

**Comment by gkwan-ibm** [comment]
close
- cannot be reproduced the problem
- and we do not have enough information to diagnose the problem
 
@tstephen  if you still have the problem, you may reopen this issue and tell us what you or Emily did to fix the problem.
