### ISSUE TITLE
Feeback

### ISSUE THREAD

**Issue by leochr** [OpenLiberty/guide-containerize-podman#9]
The guide looks good. Few suggestions:

- [x] #10

-  [x] _"In this case, you are setting the default.http.port environment variable to 9091 for the inventory container."_ 
   - add a statement about -p 9091:9091 - maps local port to the new container port specified via the environment variable
   
- [x] _"The COPY instructions use the 1001 user ID and 0 group because the icr.io/appcafe/open-liberty:full-java11-openj9-ubi image runs by default with the USER 1001"_
   - Suggestion: _The COPY instructions use the 1001 user ID and 0 group because **all official Open Liberty base images**, including icr.io/appcafe/open-liberty:full-java11-openj9-ubi used in this case, run by default with the USER 1001_
   
- [x] _"In this case, you’re using the recommended production image from the IBM container registry, icr.io/appcafe/open-liberty:full-java11-openj9-ubi, as your parent image. If you don’t want any additional runtime features for your kernel image, define the FROM instruction as FROM icr.io/appcafe/open-liberty:kernel-java11-openj9-ubi. To use the default image that comes with the Open Liberty runtime, define the FROM instruction as FROM icr.io/appcafe/open-liberty. You can find all the official images and ubi images on the open-liberty Docker Hub."_
     - IBM container registry --> IBM Container Registry (ICR)
     - Instead of using the links to Docker Hub, use this link. It lists both Docker Hub as well as ICR : https://github.com/OpenLiberty/ci.docker#container-images
     - "full" tag-based images provide all Liberty features and are provided for convenience only. It comes with a large footprint. It's ideal for development. That is not what we should recommend customers use in production. Customers should instead use kernel-slim to start with the bare minimum server and expand it with the necessary features by using the features.sh provided with base image. See usage pattern at https://github.com/OpenLiberty/ci.docker#building-an-application-image

**Comment by gkwan-ibm** [comment]
close
- PR was approved and merged
